[package]
name = "tui"
version = "0.3.0-beta.0"
authors = ["Florian Dehau <work@fdehau.com>"]
description = """
A library to build rich terminal user interfaces or dashboards
"""
keywords = ["tui", "terminal", "dashboard"]
repository = "https://github.com/fdehau/tui-rs"
license = "MIT"
exclude = ["docs/*", ".travis.yml"]
autoexamples = true

[badges]
travis-ci = { repository = "fdehau/tui-rs" }

[features]
default = ["termion"]

[dependencies]
bitflags = "1.0"
cassowary = "0.3"
itertools = "0.7"
log = "0.4"
either = "1.5"
unicode-segmentation = "1.2"
unicode-width = "0.1"
termion = { version = "1.5", optional = true }
rustbox = { version = "0.11", optional = true }
crossterm = { version = "0.4", optional = true }

[dev-dependencies]
stderrlog = "0.4"
rand = "0.4"

[[example]]
name = "rustbox"
path = "examples/rustbox.rs"
required-features = ["rustbox"]

[[example]]
name = "crossterm"
path = "examples/crossterm.rs"
required-features = ["crossterm"]
